export enum TOKENSTYPES {
    SET_TOKEN = "SET_TOKEN",
    CLEAR_TOKEN = "CLEAR_TOKEN",
    FETCH_SET_TOKEN = "FETCH_SET_TOKEN",
    FETCH_CLEAR_TOKEN = "FETCH_CLEAR_TOKEN",
    WATCH_CLEAR_TOKEN = "WATCH_CLEAR_TOKEN",
}
